In [36]:
# Reformat datasets into adjacency matrices

# Facebook data from: https://snap.stanford.edu/data/ego-Facebook.html

# Potential others:
# - Graph representation of organic solar cell
#       (https://data.mendeley.com/datasets/rvdnt639c2/2)
# - 

In [37]:
import gzip
import numpy as np
import os
# import localsolver

In [38]:
# Facebook data, 4039 nodes
matrix = np.zeros((4039, 4039), dtype=int)
with gzip.open("facebook_combined.txt.gz", "rt") as f:
    content = f.readlines()
    
    for line in content:
        friend = line.split()
        matrix[int(friend[0])][int(friend[1])] += 1
        matrix[int(friend[1])][int(friend[0])] += 1
    f.close()
    
print(matrix)


[[0 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
files = os.listdir("facebook/")
print(files)
for file in files:
    if ".edges" in file:
        with open("facebook/"+file, "rt") as f:
            content = f.readlines()
            count = 0
            for line in content:
                # print(line)
                count += 1
            print(count)
            if count == 292:
                print(file)
            f.close()

['0.circles', '0.edges', '0.egofeat', '0.feat', '0.featnames', '107.circles', '107.edges', '107.egofeat', '107.feat', '107.featnames', '1684.circles', '1684.edges', '1684.egofeat', '1684.feat', '1684.featnames', '1912.circles', '1912.edges', '1912.egofeat', '1912.feat', '1912.featnames', '3437.circles', '3437.edges', '3437.egofeat', '3437.feat', '3437.featnames', '348.circles', '348.edges', '348.egofeat', '348.feat', '348.featnames', '3980.circles', '3980.edges', '3980.egofeat', '3980.feat', '3980.featnames', '414.circles', '414.edges', '414.egofeat', '414.feat', '414.featnames', '686.circles', '686.edges', '686.egofeat', '686.feat', '686.featnames', '698.circles', '698.edges', '698.egofeat', '698.feat', '698.featnames']
5038
53498
28048
60050
9626
6384
292
3980.edges
3386
3312
540


In [43]:
matrix2 = np.zeros((52, 52), dtype=int)
with open("facebook/3980.edges", "rt") as f:
    content = f.readlines()
    nodes = dict()
    i = 0
    for line in content:
        edge = line.split()
        if edge[0] not in nodes:
            nodes[edge[0]] = i
            i += 1
        if edge[1] not in nodes:
            nodes[edge[1]] = i
            i += 1
        matrix2[nodes[edge[0]]][nodes[edge[1]]] = 1
        matrix2[nodes[edge[1]]][nodes[edge[0]]] = 1
    print(nodes)
print(len(nodes), max(nodes), min(nodes), 292/(52*52))
for i in range(len(matrix2)):
    for j in range(len(matrix2)):
        if j < i or j == i:
            print(matrix2[i][j], " ", end="")
    print()

{'4038': 0, '4014': 1, '4032': 2, '4027': 3, '4019': 4, '4026': 5, '4023': 6, '4003': 7, '4018': 8, '3997': 9, '4031': 10, '4021': 11, '3998': 12, '4013': 13, '4004': 14, '4030': 15, '3988': 16, '3982': 17, '4002': 18, '4037': 19, '4020': 20, '3995': 21, '3993': 22, '3986': 23, '4017': 24, '3983': 25, '3994': 26, '3999': 27, '4005': 28, '4009': 29, '3991': 30, '3989': 31, '4011': 32, '3992': 33, '3981': 34, '4000': 35, '3985': 36, '594': 37, '3996': 38, '4029': 39, '4001': 40, '4025': 41, '4016': 42, '4034': 43, '3990': 44, '4036': 45, '4033': 46, '4007': 47, '4028': 48, '4012': 49, '3987': 50, '4006': 51}
52 594 3981 0.10798816568047337
0  
1  0  
0  0  0  
1  0  1  0  
0  0  0  0  0  
0  0  0  0  1  0  
1  1  0  0  0  0  0  
0  0  0  0  0  0  1  0  
0  0  0  0  0  0  1  0  0  
0  0  0  0  1  0  1  0  1  0  
1  0  0  1  0  0  1  0  0  0  0  
0  1  0  0  0  1  0  0  0  1  0  0  
0  1  0  0  1  0  1  0  1  1  0  1  0  
1  0  0  0  0  0  1  0  0  0  1  0  0  0  
1  0  0  0  0  0  1  0  0

In [41]:
# Code for Max cut solver from https://www.localsolver.com/docs/last/exampletour/maxcut.html
# with localsolver.LocalSolver() as ls:
    
#     #
#     # Declares the optimization model
#     #
#     model = ls.model

#     # Decision variables x[i]
#     # Is true if vertex x[i] is on the right side of the cut and false if it is on the left side of the cut
#     x = [model.bool() for i in range(n)]

#     # incut[e] is true if its endpoints are in different class of the partition
#     incut = [None]*m
#     for e in range(m):
#         incut[e] = model.neq(x[origin[e] - 1], x[dest[e] - 1])

#     # Size of the cut
#     cut_weight = model.sum(w[e]*incut[e] for e in range(m))
#     model.maximize(cut_weight)

#     model.close()

#     #
#     # Param
#     #
#     if len(sys.argv) >= 4: ls.param.time_limit = int(sys.argv[3])
#     else: ls.param.time_limit = 10

#     ls.solve()