In [24]:
# Reformat datasets into adjacency matrices

# Facebook data from: https://snap.stanford.edu/data/ego-Facebook.html

# Potential others:
# - Graph representation of organic solar cell
#       (https://data.mendeley.com/datasets/rvdnt639c2/2)
# - 

In [25]:
import gzip
import numpy as np
# import localsolver

ModuleNotFoundError: No module named 'localsolver'

In [26]:
# Facebook data, 4039 nodes
matrix = np.zeros((4039, 4039), dtype=int)
with gzip.open("facebook_combined.txt.gz", "rt") as f:
    content = f.readlines()
    
    for line in content:
        friend = line.split()
        matrix[int(friend[0])][int(friend[1])] += 1
        matrix[int(friend[1])][int(friend[0])] += 1
    f.close()
    
print(matrix)


[[0 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# Code for Max cut solver from https://www.localsolver.com/docs/last/exampletour/maxcut.html
# with localsolver.LocalSolver() as ls:
    
#     #
#     # Declares the optimization model
#     #
#     model = ls.model

#     # Decision variables x[i]
#     # Is true if vertex x[i] is on the right side of the cut and false if it is on the left side of the cut
#     x = [model.bool() for i in range(n)]

#     # incut[e] is true if its endpoints are in different class of the partition
#     incut = [None]*m
#     for e in range(m):
#         incut[e] = model.neq(x[origin[e] - 1], x[dest[e] - 1])

#     # Size of the cut
#     cut_weight = model.sum(w[e]*incut[e] for e in range(m))
#     model.maximize(cut_weight)

#     model.close()

#     #
#     # Param
#     #
#     if len(sys.argv) >= 4: ls.param.time_limit = int(sys.argv[3])
#     else: ls.param.time_limit = 10

#     ls.solve()